<?php

namespace App\Services;

use Illuminate\Support\Facades\Log;
use Symfony\Component\Process\Exception\ProcessTimedOutException;
use Symfony\Component\Process\Process;

class VideoProbeService
{
    /**
     * @return array<string, mixed>
     */
    public function probe(string $absolutePath): array
    {
        $ffprobe = app(MediaBinaryDetector::class)->ffprobe();
        if (! $ffprobe || ! is_file($absolutePath)) {
            return [];
        }

        return $this->runProbe($ffprobe, $absolutePath, false);
    }

    /**
     * Probe a URL generated by our configured object-storage disk. The bounded
     * read timeout keeps a broken remote object from blocking reconciliation.
     *
     * @return array<string, mixed>
     */
    public function probeRemote(string $url): array
    {
        $ffprobe = app(MediaBinaryDetector::class)->ffprobe();
        if (! $ffprobe || filter_var($url, FILTER_VALIDATE_URL) === false) {
            return [];
        }

        return $this->runProbe($ffprobe, $url, true);
    }

    /**
     * Read the actual primary packet timelines without trusting container
     * Duration metadata. This is deliberately an exceptional diagnostic: a
     * normal probe is cheap; a packet scan walks the entire file and is used
     * only when an encode disagrees with an input whose stream durations are
     * absent or untrustworthy (a common Matroska failure mode).
     *
     * A successful scan answers the important forensic question precisely:
     * do media packets really exist after the apparent output end, or is the
     * MKV Segment/Info duration simply wrong? A timed-out or failed scan is
     * never used as a partial duration.
     *
     * @return array<string, mixed>
     */
    public function packetTimeline(string $absolutePath): array
    {
        $ffprobe = app(MediaBinaryDetector::class)->ffprobe();
        if (! $ffprobe || ! is_file($absolutePath)) {
            return [
                'complete' => false,
                'source' => 'unavailable',
                'reason' => 'FFprobe or the local input file is unavailable.',
            ];
        }

        $video = $this->packetTimelineForStream($ffprobe, $absolutePath, 'v:0');
        $audio = $this->packetTimelineForStream($ffprobe, $absolutePath, 'a:0');
        $videoEnd = $video['end_seconds'] ?? null;
        $audioEnd = $audio['end_seconds'] ?? null;
        $complete = (bool) ($video['complete'] ?? false) || (bool) ($audio['complete'] ?? false);

        return array_filter([
            'complete' => $complete,
            'source' => 'ffprobe_packet_timestamps',
            'video_end_seconds' => $videoEnd,
            'audio_end_seconds' => $audioEnd,
            'primary_av_end_seconds' => max((float) ($videoEnd ?? 0), (float) ($audioEnd ?? 0)) ?: null,
            'video_packets' => $video['packets'] ?? 0,
            'audio_packets' => $audio['packets'] ?? 0,
            'video_scan' => $video['reason'] ?? null,
            'audio_scan' => $audio['reason'] ?? null,
        ], static fn ($value): bool => $value !== null && $value !== '');
    }

    /**
     * @return array{complete: bool, end_seconds?: float, packets: int, reason?: string}
     */
    private function packetTimelineForStream(string $ffprobe, string $absolutePath, string $selector): array
    {
        $timeout = max(0, (int) config('cdn.ffprobe_packet_timeline_timeout_seconds', 0));
        $process = new Process([
            $ffprobe,
            '-v', 'error',
            '-select_streams', $selector,
            '-show_entries', 'packet=pts_time,dts_time,duration_time',
            '-of', 'csv=p=0',
            $absolutePath,
        ]);
        // The output contains a line per packet; consume it incrementally so
        // a multi-hour movie does not become a multi-megabyte PHP string.
        $process->disableOutput();
        $process->setTimeout($timeout > 0 ? (float) $timeout : null);

        $lineBuffer = '';
        $packets = 0;
        $end = null;
        $consume = static function (string $chunk) use (&$lineBuffer, &$packets, &$end): void {
            $lineBuffer .= str_replace("\r", '', $chunk);
            while (($newline = strpos($lineBuffer, "\n")) !== false) {
                $line = trim(substr($lineBuffer, 0, $newline));
                $lineBuffer = substr($lineBuffer, $newline + 1);
                if ($line === '') {
                    continue;
                }
                $columns = str_getcsv($line);
                $pts = isset($columns[0]) && is_numeric($columns[0]) ? (float) $columns[0] : null;
                $dts = isset($columns[1]) && is_numeric($columns[1]) ? (float) $columns[1] : null;
                $duration = isset($columns[2]) && is_numeric($columns[2]) ? max(0.0, (float) $columns[2]) : 0.0;
                $timestamp = max((float) ($pts ?? -INF), (float) ($dts ?? -INF));
                if (! is_finite($timestamp)) {
                    continue;
                }
                $packets++;
                $candidate = $timestamp + $duration;
                $end = $end === null ? $candidate : max($end, $candidate);
            }
        };

        try {
            $process->run(static function (string $type, string $chunk) use ($consume): void {
                if ($type === Process::OUT) {
                    $consume($chunk);
                }
            });
            if ($lineBuffer !== '') {
                $consume($lineBuffer."\n");
            }
        } catch (ProcessTimedOutException $exception) {
            Log::warning('video_probe.packet_timeline_timed_out', [
                'target' => basename($absolutePath),
                'stream' => $selector,
                'timeout' => $process->getTimeout(),
            ]);

            return ['complete' => false, 'packets' => $packets, 'reason' => 'packet scan timed out'];
        }

        if (! $process->isSuccessful()) {
            return [
                'complete' => false,
                'packets' => $packets,
                // Output is intentionally disabled because packet listings can
                // be very large. The exit code remains durable diagnostic
                // evidence without retaining a movie's worth of ffprobe text.
                'reason' => 'packet scan failed with exit code '.($process->getExitCode() ?? 'unknown'),
            ];
        }

        return array_filter([
            'complete' => $packets > 0 && $end !== null,
            'end_seconds' => $end !== null ? round($end, 6) : null,
            'packets' => $packets,
            'reason' => $packets > 0 ? null : 'no packets in selected stream',
        ], static fn ($value): bool => $value !== null && $value !== '');
    }

    /**
     * @return array<string, mixed>
     */
    private function runProbe(string $ffprobe, string $target, bool $remote): array
    {
        $remoteOptions = $remote ? ['-rw_timeout', '15000000', '-probesize', '8000000', '-analyzeduration', '8000000'] : [];

        $process = new Process([
            $ffprobe,
            '-v', 'error',
            ...$remoteOptions,
            '-print_format', 'json',
            '-show_format',
            '-show_streams',
            $target,
        ]);
        // A hung/stalled ffprobe on a huge or borderline-corrupt file must not
        // block the queue worker indefinitely — unlike every other subprocess
        // call in this codebase, this one previously had NO timeout at all,
        // which was a likely contributor to intermittent large-file stalls.
        $process->setTimeout((float) config('cdn.ffprobe_timeout_seconds', $remote ? 60 : 120));

        try {
            $process->run();
        } catch (ProcessTimedOutException $exception) {
            Log::warning('video_probe.timed_out', [
                'target' => $remote ? $target : basename($target),
                'timeout' => $process->getTimeout(),
            ]);

            return [];
        }

        if (! $process->isSuccessful()) {
            return [];
        }

        $payload = json_decode($process->getOutput(), true);
        if (! is_array($payload)) {
            return [];
        }

        $streams = is_array($payload['streams'] ?? null) ? $payload['streams'] : [];
        $format = is_array($payload['format'] ?? null) ? $payload['format'] : [];
        $video = null;
        $attachedVideo = null;
        $audio = null;
        $videoStreamCount = 0;
        $audioStreamCount = 0;
        $subtitleStreamCount = 0;
        foreach ($streams as $stream) {
            if (! is_array($stream)) {
                continue;
            }
            if (($stream['codec_type'] ?? null) === 'video') {
                $videoStreamCount++;
                $isAttachedPicture = (bool) data_get($stream, 'disposition.attached_pic', false);
                if ($isAttachedPicture && $attachedVideo === null) {
                    $attachedVideo = $stream;
                } elseif (! $isAttachedPicture && $video === null) {
                    $video = $stream;
                }
            }
            if (($stream['codec_type'] ?? null) === 'audio') {
                $audioStreamCount++;
                if ($audio === null) {
                    $audio = $stream;
                }
            }
            if (($stream['codec_type'] ?? null) === 'subtitle') {
                $subtitleStreamCount++;
            }
        }
        $diagnosticVideo = $video ?? $attachedVideo;

        $formatDuration = $this->number($format['duration'] ?? null);
        $videoDuration = $this->streamDuration($video);
        $audioDuration = $this->streamDuration($audio);
        $primaryAvDuration = max($videoDuration ?? 0, $audioDuration ?? 0) ?: null;

        return array_filter([
            'container' => isset($format['format_name']) ? (string) $format['format_name'] : null,
            'video_codec' => is_array($video) ? (string) ($video['codec_name'] ?? '') ?: null : null,
            'audio_codec' => is_array($audio) ? (string) ($audio['codec_name'] ?? '') ?: null : null,
            'pixel_format' => is_array($video) ? (string) ($video['pix_fmt'] ?? '') ?: null : null,
            'video_profile' => is_array($video) ? (string) ($video['profile'] ?? '') ?: null : null,
            'video_level' => is_array($video) && isset($video['level']) ? (int) $video['level'] : null,
            'bits_per_raw_sample' => is_array($video) && is_numeric($video['bits_per_raw_sample'] ?? null)
                ? (int) $video['bits_per_raw_sample']
                : null,
            'color_space' => is_array($video) ? (string) ($video['color_space'] ?? '') ?: null : null,
            'color_transfer' => is_array($video) ? (string) ($video['color_transfer'] ?? '') ?: null : null,
            'color_primaries' => is_array($video) ? (string) ($video['color_primaries'] ?? '') ?: null : null,
            'audio_channels' => is_array($audio) && isset($audio['channels']) ? (int) $audio['channels'] : null,
            'has_video' => $video !== null,
            'has_audio' => $audio !== null,
            'has_attached_picture' => $attachedVideo !== null,
            'video_stream_count' => $videoStreamCount,
            'audio_stream_count' => $audioStreamCount,
            'subtitle_stream_count' => $subtitleStreamCount,
            'selected_video_stream_index' => is_array($video) && isset($video['index']) ? (int) $video['index'] : null,
            'selected_audio_stream_index' => is_array($audio) && isset($audio['index']) ? (int) $audio['index'] : null,
            'diagnostic_video_stream_index' => is_array($diagnosticVideo) && isset($diagnosticVideo['index'])
                ? (int) $diagnosticVideo['index']
                : null,
            'width' => is_array($video) && isset($video['width']) ? (int) $video['width'] : null,
            'height' => is_array($video) && isset($video['height']) ? (int) $video['height'] : null,
            // Keep the historical duration fields as the container estimate for
            // API compatibility, but expose every relevant timestamp separately.
            // Matroska commonly has a misleading format.duration while the
            // stream tag/duration_ts is correct, so callers must not treat this
            // one container field as the only authority.
            'duration' => $formatDuration,
            'duration_seconds' => $formatDuration !== null ? (int) round($formatDuration) : null,
            'format_duration' => $formatDuration,
            'format_start_time' => $this->numericValue($format['start_time'] ?? null),
            'video_duration' => $videoDuration,
            'video_duration_source' => $this->streamDurationSource($video),
            'video_start_time' => $this->numericValue(is_array($video) ? ($video['start_time'] ?? null) : null),
            'video_time_base' => is_array($video) ? (string) ($video['time_base'] ?? '') ?: null : null,
            'video_avg_frame_rate' => is_array($video) ? (string) ($video['avg_frame_rate'] ?? '') ?: null : null,
            'video_r_frame_rate' => is_array($video) ? (string) ($video['r_frame_rate'] ?? '') ?: null : null,
            'audio_duration' => $audioDuration,
            'audio_duration_source' => $this->streamDurationSource($audio),
            'audio_start_time' => $this->numericValue(is_array($audio) ? ($audio['start_time'] ?? null) : null),
            'audio_time_base' => is_array($audio) ? (string) ($audio['time_base'] ?? '') ?: null : null,
            'primary_av_duration' => $primaryAvDuration,
            // The primary video timeline is the most useful operational clock
            // for progress and output validation. Fall back only when it is
            // unavailable (for example, unusual raw streams).
            'processing_duration' => $videoDuration ?? $primaryAvDuration ?? $formatDuration,
            'bitrate' => isset($format['bit_rate']) ? (int) $format['bit_rate'] : null,
            'frame_rate' => is_array($video) ? $this->normalizeFrameRate((string) ($video['avg_frame_rate'] ?? $video['r_frame_rate'] ?? '')) : null,
            'file_size' => is_file($target) ? (int) filesize($target) : null,
        ], static fn ($value): bool => $value !== null && $value !== '');
    }

    private function normalizeFrameRate(string $value): ?float
    {
        if ($value === '' || $value === '0/0') {
            return null;
        }

        if (str_contains($value, '/')) {
            [$numerator, $denominator] = array_map('floatval', explode('/', $value, 2));

            return $denominator > 0 ? round($numerator / $denominator, 3) : null;
        }

        return is_numeric($value) ? (float) $value : null;
    }

    private function number(mixed $value): ?float
    {
        if (! is_numeric($value)) {
            return null;
        }

        $number = (float) $value;

        return $number > 0 ? $number : null;
    }

    private function numericValue(mixed $value): ?float
    {
        return is_numeric($value) ? (float) $value : null;
    }

    /**
     * @param  array<string, mixed>|null  $stream
     */
    private function streamDuration(?array $stream): ?float
    {
        if (! is_array($stream)) {
            return null;
        }

        if ($duration = $this->number($stream['duration'] ?? null)) {
            return $duration;
        }

        $durationTs = $this->number($stream['duration_ts'] ?? null);
        $timeBase = (string) ($stream['time_base'] ?? '');
        if ($durationTs !== null && str_contains($timeBase, '/')) {
            [$numerator, $denominator] = array_map('floatval', explode('/', $timeBase, 2));
            if ($numerator > 0 && $denominator > 0) {
                return $durationTs * ($numerator / $denominator);
            }
        }

        $tag = data_get($stream, 'tags.DURATION');
        if (is_string($tag) && preg_match('/^(\d+):(\d+):(\d+(?:\.\d+)?)$/', trim($tag), $matches) === 1) {
            return ((int) $matches[1] * 3600) + ((int) $matches[2] * 60) + (float) $matches[3];
        }

        return null;
    }

    /**
     * @param  array<string, mixed>|null  $stream
     */
    private function streamDurationSource(?array $stream): ?string
    {
        if (! is_array($stream)) {
            return null;
        }
        if ($this->number($stream['duration'] ?? null) !== null) {
            return 'stream.duration';
        }
        if ($this->number($stream['duration_ts'] ?? null) !== null && ! empty($stream['time_base'])) {
            return 'duration_ts*time_base';
        }
        if (is_string(data_get($stream, 'tags.DURATION')) && data_get($stream, 'tags.DURATION') !== '') {
            return 'tags.DURATION';
        }

        return null;
    }
}
