<?php

namespace App\Services;

use Illuminate\Support\Facades\Log;
use Symfony\Component\Process\Exception\ProcessTimedOutException;
use Symfony\Component\Process\Process;

class VideoProbeService
{
    /**
     * @return array<string, mixed>
     */
    public function probe(string $absolutePath): array
    {
        $ffprobe = app(MediaBinaryDetector::class)->ffprobe();
        if (! $ffprobe || ! is_file($absolutePath)) {
            return [];
        }

        return $this->runProbe($ffprobe, $absolutePath, false);
    }

    /**
     * Probe a URL generated by our configured object-storage disk. The bounded
     * read timeout keeps a broken remote object from blocking reconciliation.
     *
     * @return array<string, mixed>
     */
    public function probeRemote(string $url): array
    {
        $ffprobe = app(MediaBinaryDetector::class)->ffprobe();
        if (! $ffprobe || filter_var($url, FILTER_VALIDATE_URL) === false) {
            return [];
        }

        return $this->runProbe($ffprobe, $url, true);
    }

    /**
     * @return array<string, mixed>
     */
    private function runProbe(string $ffprobe, string $target, bool $remote): array
    {
        $remoteOptions = $remote ? ['-rw_timeout', '15000000', '-probesize', '8000000', '-analyzeduration', '8000000'] : [];

        $process = new Process([
            $ffprobe,
            '-v', 'error',
            ...$remoteOptions,
            '-print_format', 'json',
            '-show_format',
            '-show_streams',
            $target,
        ]);
        // A hung/stalled ffprobe on a huge or borderline-corrupt file must not
        // block the queue worker indefinitely — unlike every other subprocess
        // call in this codebase, this one previously had NO timeout at all,
        // which was a likely contributor to intermittent large-file stalls.
        $process->setTimeout((float) config('cdn.ffprobe_timeout_seconds', $remote ? 60 : 120));

        try {
            $process->run();
        } catch (ProcessTimedOutException $exception) {
            Log::warning('video_probe.timed_out', [
                'target' => $remote ? $target : basename($target),
                'timeout' => $process->getTimeout(),
            ]);

            return [];
        }

        if (! $process->isSuccessful()) {
            return [];
        }

        $payload = json_decode($process->getOutput(), true);
        if (! is_array($payload)) {
            return [];
        }

        $streams = is_array($payload['streams'] ?? null) ? $payload['streams'] : [];
        $format = is_array($payload['format'] ?? null) ? $payload['format'] : [];
        $video = null;
        $attachedVideo = null;
        $audio = null;
        $videoStreamCount = 0;
        $audioStreamCount = 0;
        $subtitleStreamCount = 0;
        foreach ($streams as $stream) {
            if (! is_array($stream)) {
                continue;
            }
            if (($stream['codec_type'] ?? null) === 'video') {
                $videoStreamCount++;
                $isAttachedPicture = (bool) data_get($stream, 'disposition.attached_pic', false);
                if ($isAttachedPicture && $attachedVideo === null) {
                    $attachedVideo = $stream;
                } elseif (! $isAttachedPicture && $video === null) {
                    $video = $stream;
                }
            }
            if (($stream['codec_type'] ?? null) === 'audio') {
                $audioStreamCount++;
                if ($audio === null) {
                    $audio = $stream;
                }
            }
            if (($stream['codec_type'] ?? null) === 'subtitle') {
                $subtitleStreamCount++;
            }
        }
        $diagnosticVideo = $video ?? $attachedVideo;

        return array_filter([
            'container' => isset($format['format_name']) ? (string) $format['format_name'] : null,
            'video_codec' => is_array($video) ? (string) ($video['codec_name'] ?? '') ?: null : null,
            'audio_codec' => is_array($audio) ? (string) ($audio['codec_name'] ?? '') ?: null : null,
            'pixel_format' => is_array($video) ? (string) ($video['pix_fmt'] ?? '') ?: null : null,
            'video_profile' => is_array($video) ? (string) ($video['profile'] ?? '') ?: null : null,
            'video_level' => is_array($video) && isset($video['level']) ? (int) $video['level'] : null,
            'bits_per_raw_sample' => is_array($video) && is_numeric($video['bits_per_raw_sample'] ?? null)
                ? (int) $video['bits_per_raw_sample']
                : null,
            'color_space' => is_array($video) ? (string) ($video['color_space'] ?? '') ?: null : null,
            'color_transfer' => is_array($video) ? (string) ($video['color_transfer'] ?? '') ?: null : null,
            'color_primaries' => is_array($video) ? (string) ($video['color_primaries'] ?? '') ?: null : null,
            'audio_channels' => is_array($audio) && isset($audio['channels']) ? (int) $audio['channels'] : null,
            'has_video' => $video !== null,
            'has_audio' => $audio !== null,
            'has_attached_picture' => $attachedVideo !== null,
            'video_stream_count' => $videoStreamCount,
            'audio_stream_count' => $audioStreamCount,
            'subtitle_stream_count' => $subtitleStreamCount,
            'selected_video_stream_index' => is_array($video) && isset($video['index']) ? (int) $video['index'] : null,
            'selected_audio_stream_index' => is_array($audio) && isset($audio['index']) ? (int) $audio['index'] : null,
            'diagnostic_video_stream_index' => is_array($diagnosticVideo) && isset($diagnosticVideo['index'])
                ? (int) $diagnosticVideo['index']
                : null,
            'width' => is_array($video) && isset($video['width']) ? (int) $video['width'] : null,
            'height' => is_array($video) && isset($video['height']) ? (int) $video['height'] : null,
            'duration' => isset($format['duration']) ? (float) $format['duration'] : null,
            'duration_seconds' => isset($format['duration']) ? (int) round((float) $format['duration']) : null,
            'bitrate' => isset($format['bit_rate']) ? (int) $format['bit_rate'] : null,
            'frame_rate' => is_array($video) ? $this->normalizeFrameRate((string) ($video['avg_frame_rate'] ?? $video['r_frame_rate'] ?? '')) : null,
            'file_size' => is_file($target) ? (int) filesize($target) : null,
        ], static fn ($value): bool => $value !== null && $value !== '');
    }

    private function normalizeFrameRate(string $value): ?float
    {
        if ($value === '' || $value === '0/0') {
            return null;
        }

        if (str_contains($value, '/')) {
            [$numerator, $denominator] = array_map('floatval', explode('/', $value, 2));

            return $denominator > 0 ? round($numerator / $denominator, 3) : null;
        }

        return is_numeric($value) ? (float) $value : null;
    }
}
