<?php

namespace App\Filament\Resources\MediaAssetResource\RelationManagers;

use App\Jobs\FetchWorkerHlsArtifactJob;
use App\Models\MediaSource;
use App\Services\MediaSourceService;
use App\Services\NbxEngineService;
use App\Services\TelegramImportDispatchService;
use App\Support\MediaUrl;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;

class MediaSourcesRelationManager extends RelationManager
{
    protected static string $relationship = 'sources';

    public static function getDescription(): string
    {
        $enabled = (bool) config('cdn.laravel_worker_enabled', false);
        $pullEnabled = (bool) config('cdn.laravel_worker_pull_enabled', true);
        $url = config('cdn.laravel_worker_api_url', '');
        if ($enabled && $url !== '') {
            $mode = $pullEnabled ? ' CDN pulls the HLS ZIP from the worker (pull mode).' : ' Worker pushes optimized + HLS back to CDN.';
            return 'Faststart runs on CDN; HLS is generated by the external Laravel worker.' . $mode . ' Use "Queue for optimization" or "Run re-optimise" to re-send a source.';
        }
        return 'Sources are optimized directly on the CDN (faststart + HLS) using the local optimization queue. To use the external Laravel worker, set CDN_LARAVEL_WORKER_ENABLED=true and CDN_LARAVEL_WORKER_PULL_ENABLED=true, then configure CDN_LARAVEL_WORKER_API_URL / CDN_LARAVEL_WORKER_API_TOKEN.';
    }

    public function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Select::make('source_type')
                ->required()
                ->live()
                ->afterStateUpdated(fn (Forms\Set $set) => $set('imported_source_id', null))
                ->options([
                    'url' => 'Direct URL',
                    'embed' => 'Embed',
                    'upload' => 'Local Upload',
                    'remote_fetch' => 'Remote Fetch',
                    'telegram' => 'Telegram',
                ]),
            Forms\Components\Textarea::make('source_url')
                ->label(fn (Forms\Get $get): string => $get('source_type') === 'telegram' ? 'Telegram Message URL' : 'Source URL or Embed URL')
                ->rows(3)
                ->visible(fn (Forms\Get $get): bool => in_array($get('source_type'), ['url', 'embed', 'remote_fetch', 'telegram'], true))
                ->required(fn (Forms\Get $get): bool => in_array($get('source_type'), ['url', 'embed', 'remote_fetch', 'telegram'], true))
                ->maxLength(2048)
                ->rule(fn (Forms\Get $get) => $get('source_type') === 'embed'
                    ? ['nullable', 'string']
                    : ['required', 'string', static function (string $attribute, mixed $value, \Closure $fail): void {
                        if (! MediaUrl::isValid(is_string($value) ? $value : null)) {
                            $fail("The {$attribute} field must be a valid URL.");
                        }
                    }]),
            Forms\Components\Placeholder::make('telegram_hint')
                ->label('Telegram Import')
                ->content('CDN will ask Telebot for capacity, then Telebot streams the Telegram video directly into this CDN source. Keep the Telebot manual UI as a fallback.')
                ->visible(fn (Forms\Get $get): bool => $get('source_type') === 'telegram'),
            Forms\Components\Hidden::make('imported_source_id')
                ->dehydrated(true),
            Forms\Components\Radio::make('import_mode')
                ->label('Remote Import Mode')
                ->default((string) config('cdn.default_import_mode', 'queue'))
                ->options([
                    'queue' => 'Queue',
                    'now' => 'Import Now',
                ])
                ->visible(fn (Forms\Get $get): bool => $get('source_type') === 'remote_fetch')
                ->dehydrated(fn (Forms\Get $get): bool => $get('source_type') === 'remote_fetch'),
            Forms\Components\FileUpload::make('upload_file')
                ->label('Video File')
                ->disk(config('cdn.disk', 'public'))
                ->directory('media/tmp')
                ->acceptedFileTypes(['video/*'])
                ->preserveFilenames()
                ->maxSize((int) config('cdn.max_upload_mb', 2048) * 1024)
                ->visible(fn (Forms\Get $get): bool => $get('source_type') === 'upload')
                ->required(fn (Forms\Get $get): bool => $get('source_type') === 'upload')
                ->helperText('For large files, upload may take time before import starts.'),
            Forms\Components\Section::make('Worker artifact (manual fallback)')
                ->description('When the worker callback failed or the CDN did not receive the artifact URL, paste the artifact URL from the worker (e.g. Copy artifact URL in worker Filament) and save. Then use "Fetch artifact from worker" in the table to download and install the HLS ZIP. Only used when editing an existing source.')
                ->schema([
                    Forms\Components\TextInput::make('hls_worker_artifact_url')
                        ->label('Worker artifact URL')
                        ->url()
                        ->maxLength(2048)
                        ->placeholder('https://worker.../api/v1/artifacts/TOKEN')
                        ->helperText('Optional. Paste the full artifact URL from the worker to allow manual fetch.')
                        ->columnSpanFull(),
                ])
                ->collapsed()
                ->visible(fn (): bool => (bool) config('cdn.laravel_worker_enabled', false)),
            Forms\Components\Toggle::make('compress_enabled')
                ->label('Compress to MP4 on optimization')
                ->default(true)
                ->helperText('When enabled, after fetch or upload the file is transcoded to H.264 MP4 (smaller size, faststart) before playback and HLS. Recommended for large MKV/AVI files.')
                ->visible(fn (Forms\Get $get): bool => in_array($get('source_type'), ['remote_fetch', 'upload'], true)),
            Forms\Components\Section::make('NBX Engine processing')
                ->description('These match the portal NBX options. Work files stay local for FFmpeg, then final outputs move to Contabo unless Local is selected.')
                ->schema([
                    Forms\Components\Select::make('storage_target')
                        ->label('Final storage')
                        ->default((string) config('nbx.default_storage', 'contabo'))
                        ->options(fn (): array => (bool) config('nbx.allow_local_storage', true)
                            ? ['contabo' => 'Contabo Object Storage', 'local' => 'Local public disk']
                            : ['contabo' => 'Contabo Object Storage'])
                        ->required(),
                    Forms\Components\Toggle::make('faststart')
                        ->label('Faststart MP4')
                        ->default((bool) config('nbx.default_faststart', true))
                        ->inline(false),
                    Forms\Components\Toggle::make('hls_480p')
                        ->label('Generate 480p HLS')
                        ->default((bool) config('nbx.default_hls_480', true))
                        ->inline(false)
                        ->helperText('Default playback quality. NBX still probes the file and will not upscale low-profile videos.'),
                    Forms\Components\Toggle::make('hls_720p')
                        ->label('Generate 720p HLS')
                        ->default((bool) config('nbx.default_hls_720', false))
                        ->inline(false)
                        ->helperText('Use selectively for monthly/Wi-Fi/hot movies only.'),
                    Forms\Components\Toggle::make('hls_1080p')
                        ->label('Generate 1080p HLS')
                        ->default((bool) config('nbx.default_hls_1080', false))
                        ->disabled(fn (): bool => ! (bool) config('nbx.allow_1080p', false))
                        ->dehydrated()
                        ->inline(false)
                        ->helperText('Disabled by Narabox policy unless NBX_ALLOW_1080P=true.'),
                    Forms\Components\Toggle::make('allow_downloads')
                        ->label('Allow MP4 download URL')
                        ->default(true)
                        ->inline(false),
                    Forms\Components\Toggle::make('allow_hls_streaming')
                        ->label('Allow HLS streaming URL')
                        ->default(true)
                        ->inline(false),
                ])
                ->columns(2)
                ->collapsible()
                ->visible(fn (Forms\Get $get): bool => in_array($get('source_type'), ['remote_fetch', 'upload', 'url'], true)),
            Forms\Components\Actions::make([
                Forms\Components\Actions\Action::make('start_remote_import')
                    ->label('Start Import Now')
                    ->icon('heroicon-o-arrow-down-tray')
                    ->color('info')
                    ->visible(fn (Forms\Get $get): bool => $get('source_type') === 'remote_fetch')
                    ->action(function (Forms\Get $get, Forms\Set $set, ?MediaSource $record): void {
                        $sourceUrl = $this->normalizeSourceUrl($get('source_url'), 'remote_fetch');
                        $importMode = (string) ($get('import_mode') ?? config('cdn.default_import_mode', 'queue'));

                        if ($sourceUrl === null || ! MediaUrl::isValid($sourceUrl)) {
                            Notification::make()
                                ->warning()
                                ->title('Source URL is required')
                                ->body('Please add a valid URL before starting import.')
                                ->send();
                            return;
                        }

                        $service = app(MediaSourceService::class);
                        $isActive = (bool) ($get('is_active') ?? true);

                        if ($record) {
                            $record->update([
                                'source_type' => 'remote_fetch',
                                'source_url' => $sourceUrl,
                                'is_active' => $isActive,
                                'compress_enabled' => (bool) ($get('compress_enabled') ?? true),
                                'source_metadata' => $this->mergeNbxMetadata($record, $this->nbxProcessingPayloadFromGet($get, 'remote_fetch')),
                            ]);
                            if ($importMode === 'now') {
                                $service->importRemoteNow($record);
                                $record->refresh();
                            } else {
                                $service->queueRemoteImport($record);
                            }
                            $set('imported_source_id', $record->id);

                            if ($importMode === 'now') {
                                if ($record->status === 'failed') {
                                    Notification::make()
                                        ->danger()
                                        ->title('Import failed')
                                        ->body($record->failure_reason ?: 'Remote import failed.')
                                        ->send();
                                } else {
                                    Notification::make()
                                        ->success()
                                        ->title('Import completed')
                                        ->body('Remote media was imported successfully.')
                                        ->send();
                                }
                            } else {
                                Notification::make()
                                    ->info()
                                    ->title('Import queued')
                                    ->body('Re-import queued. Progress is updating in the table.')
                                    ->send();
                            }

                            return;
                        }

                        $asset = $this->getOwnerRecord();
                        $source = MediaSource::create([
                            'media_asset_id' => $asset->id,
                            'source_type' => 'remote_fetch',
                            'source_url' => $sourceUrl,
                            'status' => 'pending',
                            'is_active' => $isActive,
                            'compress_enabled' => (bool) ($get('compress_enabled') ?? true),
                            'source_metadata' => app(NbxEngineService::class)->initialMetadata($this->nbxProcessingPayloadFromGet($get, 'remote_fetch'), 'remote_fetch'),
                        ]);

                        if ($importMode === 'now') {
                            $service->importRemoteNow($source);
                            $source->refresh();
                        } else {
                            $service->queueRemoteImport($source);
                        }
                        $set('imported_source_id', $source->id);

                        if ($importMode === 'now') {
                            if ($source->status === 'failed') {
                                Notification::make()
                                    ->danger()
                                    ->title('Import failed')
                                    ->body($source->failure_reason ?: 'Remote import failed.')
                                    ->send();
                            } else {
                                Notification::make()
                                    ->success()
                                    ->title('Import completed')
                                    ->body('Source was created and imported immediately.')
                                    ->send();
                            }
                        } else {
                            Notification::make()
                                ->info()
                                ->title('Import queued and auto-saved')
                                ->body('Source has been created. You can close this dialog and watch progress.')
                                ->send();
                        }
                    }),
            ]),
            Forms\Components\Toggle::make('is_active')
                ->default(true),
            Forms\Components\Placeholder::make('import_progress')
                ->label('Import Progress')
                ->content(function (?MediaSource $record): string {
                    if (! $record) {
                        return 'Progress will appear after source is created.';
                    }

                    $metadata = (array) ($record->source_metadata ?? []);
                    if (($metadata['source'] ?? null) === 'telegram') {
                        $telebotStatus = strtoupper((string) ($metadata['telebot_status'] ?? 'queued'));
                        $message = (string) ($metadata['telebot_message'] ?? '');
                        $suffix = $message !== '' ? " - {$message}" : '';
                        return "TELEGRAM {$telebotStatus}{$suffix}";
                    }

                    $percent = (int) ($record->progress_percent ?? 0);
                    $downloaded = $record->bytes_downloaded ? $this->formatBytes((int) $record->bytes_downloaded) : '0 B';
                    $total = $record->bytes_total ? $this->formatBytes((int) $record->bytes_total) : 'Unknown total';
                    $status = strtoupper($record->status);

                    return "{$status} - {$percent}% ({$downloaded} / {$total})";
                })
                ->visible(fn (?MediaSource $record): bool => (bool) $record),
            Forms\Components\Textarea::make('failure_reason')
                ->disabled()
                ->dehydrated(false)
                ->rows(2)
                ->visible(fn (?MediaSource $record): bool => (bool) $record?->failure_reason),
            Forms\Components\Textarea::make('last_error')
                ->disabled()
                ->dehydrated(false)
                ->rows(3)
                ->visible(fn (?MediaSource $record): bool => (bool) $record?->last_error),
        ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->description(self::getDescription())
            ->poll((string) config('cdn.admin_sources_polling_interval', '15s'))
            ->columns([
                Tables\Columns\TextColumn::make('id')
                    ->sortable(),
                Tables\Columns\TextColumn::make('source_type')
                    ->badge()
                    ->formatStateUsing(function (string $state, MediaSource $record): string {
                        $metadata = (array) ($record->source_metadata ?? []);

                        return ($metadata['source'] ?? null) === 'telegram' ? 'telegram' : $state;
                    }),
                Tables\Columns\TextColumn::make('source_metadata.telebot_status')
                    ->label('Telebot')
                    ->badge()
                    ->placeholder('—')
                    ->formatStateUsing(fn (?string $state): string => strtoupper((string) ($state ?: '—')))
                    ->color(fn (?string $state): string => match ($state) {
                        'done' => 'success',
                        'failed', 'cancelled' => 'danger',
                        'waiting_for_capacity' => 'warning',
                        'queued', 'downloading', 'uploading' => 'info',
                        default => 'gray',
                    })
                    ->description(fn (MediaSource $record): ?string => ((array) ($record->source_metadata ?? []))['telebot_message'] ?? null)
                    ->toggleable(),
                Tables\Columns\TextColumn::make('status')
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'ready' => 'success',
                        'failed' => 'danger',
                        'downloading', 'processing', 'proxying', 'uploading' => 'warning',
                        default => 'info',
                    }),
                Tables\Columns\IconColumn::make('is_active')
                    ->boolean(),
                Tables\Columns\IconColumn::make('compress_enabled')
                    ->label('Compress')
                    ->boolean()
                    ->trueIcon('heroicon-o-archive-box')
                    ->falseIcon('heroicon-o-document')
                    ->trueColor('success')
                    ->falseColor('gray')
                    ->sortable()
                    ->toggleable(),
                Tables\Columns\TextColumn::make('mime_type')
                    ->toggleable(),
                Tables\Columns\TextColumn::make('playback_type')
                    ->label('Playback')
                    ->badge()
                    ->formatStateUsing(fn (?string $state): string => strtoupper((string) ($state ?: 'mp4')))
                    ->color(fn (?string $state): string => $state === 'hls' ? 'success' : 'info')
                    ->toggleable(),
                Tables\Columns\TextColumn::make('hls_worker_status')
                    ->label('HLS Worker')
                    ->badge()
                    ->color(fn (?string $state): string => match ($state) {
                        'queued', 'artifact_ready', 'fetching', 'installing' => 'warning',
                        'completed', 'partial' => 'success',
                        'failed' => 'danger',
                        default => 'gray',
                    })
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('hls_worker_last_error')
                    ->label('Worker Error')
                    ->limit(40)
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('optimize_status')
                    ->label('Optimize')
                    ->badge()
                    ->formatStateUsing(fn (?string $state): string => strtoupper((string) ($state ?: 'pending')))
                    ->color(fn (?string $state): string => match ($state) {
                        'ready' => 'success',
                        'failed' => 'danger',
                        'processing', 'pending' => 'warning',
                        default => 'gray',
                    })
                    ->description(fn (MediaSource $record): ?string => $record->optimize_status === 'failed' && $record->optimize_error ? $record->optimize_error : null)
                    ->toggleable(),
                Tables\Columns\TextColumn::make('file_size_bytes')
                    ->label('Size')
                    ->formatStateUsing(fn (?int $state): string => $state ? $this->formatBytes($state) : '-'),
                Tables\Columns\TextColumn::make('progress_percent')
                    ->label('Progress')
                    ->formatStateUsing(fn (?int $state): string => (($state ?? 0) . '%'))
                    ->description(function (MediaSource $record): string {
                        $downloaded = $record->bytes_downloaded ? $this->formatBytes((int) $record->bytes_downloaded) : '0 B';
                        $total = $record->bytes_total ? $this->formatBytes((int) $record->bytes_total) : 'Unknown';
                        return "{$downloaded} / {$total}";
                    })
                    ->badge()
                    ->color(fn (MediaSource $record): string => match ($record->status) {
                        'ready' => 'success',
                        'failed' => 'danger',
                        default => 'warning',
                    }),
                Tables\Columns\TextColumn::make('public_url')
                    ->label('Public URL')
                    ->state(fn (MediaSource $record) => app(MediaSourceService::class)->buildPublicUrl($record))
                    ->copyable()
                    ->toggleable(),
                Tables\Columns\TextColumn::make('hls_master_url')
                    ->label('HLS Master URL')
                    ->state(function (MediaSource $record): ?string {
                        $playback = app(MediaSourceService::class)->buildPlaybackManifest($record);
                        return isset($playback['hls_master_url']) ? (string) $playback['hls_master_url'] : null;
                    })
                    ->copyable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('mp4_play_url')
                    ->label('MP4 Playback URL')
                    ->state(function (MediaSource $record): ?string {
                        $playback = app(MediaSourceService::class)->buildPlaybackManifest($record);
                        return isset($playback['mp4_play_url']) ? (string) $playback['mp4_play_url'] : null;
                    })
                    ->copyable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('download_url')
                    ->label('Download URL')
                    ->state(function (MediaSource $record): ?string {
                        $playback = app(MediaSourceService::class)->buildPlaybackManifest($record);
                        return isset($playback['download_url']) ? (string) $playback['download_url'] : null;
                    })
                    ->copyable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->since(),
            ])
            ->headerActions([
                Tables\Actions\CreateAction::make()
                    ->label('Import Source')
                    ->using(function (array $data): MediaSource {
                        $asset = $this->getOwnerRecord();
                        $service = app(MediaSourceService::class);

                        $sourceType = $data['source_type'];
                        $sourceUrl = $this->normalizeSourceUrl($data['source_url'] ?? null, $sourceType);
                        $importedSourceId = isset($data['imported_source_id']) ? (int) $data['imported_source_id'] : null;
                        $importMode = (string) ($data['import_mode'] ?? config('cdn.default_import_mode', 'queue'));

                        if ($sourceType === 'telegram') {
                            if ($sourceUrl === null || ! MediaUrl::isValid($sourceUrl)) {
                                throw new \RuntimeException('Please enter a valid Telegram message URL.');
                            }

                            $source = MediaSource::create([
                                'media_asset_id' => $asset->id,
                                'source_type' => 'remote_fetch',
                                'source_url' => $sourceUrl,
                                'status' => 'pending',
                                'is_active' => (bool) ($data['is_active'] ?? true),
                                'compress_enabled' => true,
                                'source_metadata' => [
                                    'source' => 'telegram',
                                    'telegram_url' => $sourceUrl,
                                    'telebot_status' => 'waiting_for_capacity',
                                    'telebot_message' => 'Waiting to dispatch to Telebot.',
                                ],
                            ]);

                            $dispatched = app(TelegramImportDispatchService::class)->dispatch($source);

                            $notification = Notification::make()
                                ->title($dispatched ? 'Telegram import sent to Telebot' : 'Telegram import waiting')
                                ->body($dispatched
                                    ? 'Telebot is streaming the Telegram file into this CDN source.'
                                    : 'Telebot is busy or unavailable. The scheduler will retry dispatching this source.');

                            ($dispatched ? $notification->success() : $notification->warning())->send();

                            return $source->fresh();
                        }

                        if ($sourceType === 'remote_fetch' && $importedSourceId) {
                            $existing = MediaSource::where('id', $importedSourceId)
                                ->where('media_asset_id', $asset->id)
                                ->first();

                            if ($existing) {
                                $existing->update([
                                    'source_url' => $sourceUrl ?? $existing->source_url,
                                    'is_active' => (bool) ($data['is_active'] ?? $existing->is_active),
                                    'compress_enabled' => (bool) ($data['compress_enabled'] ?? $existing->compress_enabled),
                                    'source_metadata' => $this->mergeNbxMetadata($existing, $this->nbxProcessingPayload($data, 'remote_fetch')),
                                ]);

                                return $existing->fresh();
                            }
                        }

                        if ($sourceType === 'upload') {
                            $source = $service->attachStoredUpload($asset, (string) $data['upload_file']);
                            $source->update([
                                'compress_enabled' => (bool) ($data['compress_enabled'] ?? true),
                                'source_metadata' => $this->mergeNbxMetadata($source, $this->nbxProcessingPayload($data, 'upload')),
                            ]);
                            Notification::make()
                                ->success()
                                ->title('Upload import started')
                                ->body('Local upload was attached and processed.')
                                ->send();
                            return $source;
                        }

                        $source = MediaSource::create([
                            'media_asset_id' => $asset->id,
                            'source_type' => $sourceType,
                            'source_url' => $sourceUrl,
                            'status' => in_array($sourceType, ['url', 'embed'], true) ? 'ready' : 'pending',
                            'is_active' => (bool) ($data['is_active'] ?? true),
                            'compress_enabled' => (bool) ($data['compress_enabled'] ?? true),
                            'source_metadata' => app(NbxEngineService::class)->initialMetadata($this->nbxProcessingPayload($data, $sourceType), $sourceType),
                        ]);

                        if ($sourceType === 'remote_fetch') {
                            if ($importMode === 'now') {
                                $service->importRemoteNow($source);
                                $source->refresh();
                            } else {
                                $service->queueRemoteImport($source);
                            }
                            if ($importMode === 'now') {
                                if ($source->status === 'failed') {
                                    Notification::make()
                                        ->danger()
                                        ->title('Remote import failed')
                                        ->body($source->failure_reason ?: 'Remote import failed.')
                                        ->send();
                                } else {
                                    Notification::make()
                                        ->success()
                                        ->title('Remote import completed')
                                        ->body('Real-time import completed successfully.')
                                        ->send();
                                }
                            } else {
                                Notification::make()
                                    ->info()
                                    ->title('Remote import queued')
                                    ->body('Use the progress column to monitor download and processing.')
                                    ->send();
                            }
                        } else {
                            $service->refreshAssetStatus($asset);
                        }

                        return $source->fresh();
                    }),
            ])
            ->actions([
                Tables\Actions\Action::make('copy_urls')
                    ->label('Copy URLs')
                    ->icon('heroicon-o-clipboard-document')
                    ->visible(fn (MediaSource $record): bool => $record->status === 'ready')
                    ->fillForm(function (MediaSource $record): array {
                        $service = app(MediaSourceService::class);
                        $playback = $service->buildPlaybackManifest($record);

                        return [
                            'copy_hls_master_url' => (string) ($playback['hls_master_url'] ?? ''),
                            'copy_mp4_play_url' => (string) (($playback['mp4_play_url'] ?? $playback['mp4_url'] ?? '') ?: ''),
                            'copy_download_url' => (string) ($playback['download_url'] ?? ''),
                        ];
                    })
                    ->form([
                        Forms\Components\TextInput::make('copy_hls_master_url')
                            ->label('HLS Master URL')
                            ->readOnly()
                            ->helperText('HLS is streaming-only. If blank, the master playlist is not available yet.')
                            ->suffixAction(
                                Forms\Components\Actions\Action::make('copy_hls_master_url_btn')
                                    ->icon('heroicon-o-clipboard-document')
                                    ->action(function (Forms\Get $get): void {
                                        $url = trim((string) $get('copy_hls_master_url'));
                                        if ($url === '') {
                                            Notification::make()
                                                ->warning()
                                                ->title('HLS is not ready yet')
                                                ->body('HLS master playlist is not available yet.')
                                                ->send();

                                            return;
                                        }

                                        Notification::make()
                                            ->success()
                                            ->title('Copied HLS URL')
                                            ->body($url)
                                            ->send();
                                    })
                            ),
                        Forms\Components\TextInput::make('copy_mp4_play_url')
                            ->label('MP4 Playback URL')
                            ->readOnly(),
                        Forms\Components\TextInput::make('copy_download_url')
                            ->label('Download URL (Original MP4)')
                            ->readOnly(),
                    ])
                    ->modalSubmitAction(false),
                Tables\Actions\EditAction::make()
                    ->mutateRecordDataUsing(function (array $data): array {
                        $data['upload_file'] = null;
                        $metadata = (array) ($data['source_metadata'] ?? []);
                        if (($metadata['source'] ?? null) === 'telegram') {
                            $data['source_type'] = 'telegram';
                            $data['source_url'] = $metadata['telegram_url'] ?? $data['source_url'] ?? null;
                        }
                        $nbx = is_array($metadata['nbx'] ?? null) ? $metadata['nbx'] : [];
                        $requested = is_array($nbx['requested'] ?? null) ? $nbx['requested'] : [];
                        $hls = is_array($requested['hls'] ?? null) ? $requested['hls'] : [];

                        $data['storage_target'] = $nbx['storage_target'] ?? config('nbx.default_storage', 'contabo');
                        $data['faststart'] = (bool) ($requested['faststart'] ?? config('nbx.default_faststart', true));
                        $data['hls_480p'] = (bool) ($hls['480p'] ?? config('nbx.default_hls_480', true));
                        $data['hls_720p'] = (bool) ($hls['720p'] ?? config('nbx.default_hls_720', false));
                        $data['hls_1080p'] = (bool) ($hls['1080p'] ?? config('nbx.default_hls_1080', false));
                        $data['allow_downloads'] = (bool) ($requested['allow_downloads'] ?? true);
                        $data['allow_hls_streaming'] = (bool) ($requested['allow_hls_streaming'] ?? true);

                        return $data;
                    })
                    ->using(function (MediaSource $record, array $data): MediaSource {
                        $service = app(MediaSourceService::class);
                        $sourceType = $data['source_type'] ?? $record->source_type;
                        $sourceUrl = $this->normalizeSourceUrl($data['source_url'] ?? null, $sourceType);
                        $importMode = (string) ($data['import_mode'] ?? config('cdn.default_import_mode', 'queue'));

                        if ($sourceType === 'telegram') {
                            if ($sourceUrl === null || ! MediaUrl::isValid($sourceUrl)) {
                                throw new \RuntimeException('Please enter a valid Telegram message URL.');
                            }

                            $metadata = array_merge((array) ($record->source_metadata ?? []), [
                                'source' => 'telegram',
                                'telegram_url' => $sourceUrl,
                                'telebot_status' => 'waiting_for_capacity',
                                'telebot_message' => 'Waiting to dispatch to Telebot.',
                            ]);

                            $record->update([
                                'source_type' => 'remote_fetch',
                                'source_url' => $sourceUrl,
                                'status' => 'pending',
                                'progress_percent' => 0,
                                'bytes_downloaded' => null,
                                'bytes_total' => null,
                                'is_active' => (bool) ($data['is_active'] ?? $record->is_active),
                                'compress_enabled' => true,
                                'source_metadata' => $metadata,
                            ]);

                            app(TelegramImportDispatchService::class)->dispatch($record->fresh());

                            return $record->fresh();
                        }

                        if ($sourceType === 'upload' && ! empty($data['upload_file'])) {
                            $source = $service->replaceStoredUpload($record, (string) $data['upload_file']);
                            $source->update([
                                'compress_enabled' => (bool) ($data['compress_enabled'] ?? $source->compress_enabled),
                                'source_metadata' => $this->mergeNbxMetadata($source, $this->nbxProcessingPayload($data, 'upload')),
                            ]);

                            return $source->fresh();
                        }

                        $updates = [
                            'source_type' => $sourceType,
                            'source_url' => $sourceUrl,
                            'is_active' => (bool) ($data['is_active'] ?? $record->is_active),
                        ];
                        if (array_key_exists('compress_enabled', $data)) {
                            $updates['compress_enabled'] = (bool) $data['compress_enabled'];
                        }
                        if (array_key_exists('hls_worker_artifact_url', $data)) {
                            $updates['hls_worker_artifact_url'] = trim((string) ($data['hls_worker_artifact_url'] ?? '')) ?: null;
                        }
                        $updates['source_metadata'] = $this->mergeNbxMetadata($record, $this->nbxProcessingPayload($data, $sourceType));
                        $record->update($updates);

                        if ($sourceType === 'remote_fetch' && ! empty($record->source_url)) {
                            if ($importMode === 'now') {
                                $service->importRemoteNow($record);
                            } else {
                                $service->queueRemoteImport($record);
                            }
                        } else {
                            $service->refreshAssetStatus($record->asset);
                        }

                        return $record->fresh();
                    })
                    ->after(function (): void {
                        app(MediaSourceService::class)->refreshAssetStatus($this->getOwnerRecord());
                    }),
                Tables\Actions\Action::make('refresh_telebot_status')
                    ->label('Refresh Telebot')
                    ->icon('heroicon-o-signal')
                    ->visible(function (MediaSource $record): bool {
                        $metadata = (array) ($record->source_metadata ?? []);

                        return ($metadata['source'] ?? null) === 'telegram';
                    })
                    ->action(function (MediaSource $record): void {
                        try {
                            $status = app(TelegramImportDispatchService::class)->refreshJobStatus($record);
                            app(MediaSourceService::class)->refreshAssetStatus($record->asset);

                            Notification::make()
                                ->success()
                                ->title('Telebot status refreshed')
                                ->body($status ? (string) ($status['message'] ?? $status['status'] ?? 'Updated') : 'No Telebot job id found yet.')
                                ->send();
                        } catch (\Throwable $exception) {
                            Notification::make()
                                ->warning()
                                ->title('Could not refresh Telebot')
                                ->body($exception->getMessage())
                                ->send();
                        }
                    }),
                Tables\Actions\Action::make('refresh_status')
                    ->label('Refresh')
                    ->icon('heroicon-o-arrow-path')
                    ->action(function (MediaSource $record): void {
                        app(MediaSourceService::class)->refreshAssetStatus($record->asset);
                        Notification::make()
                            ->success()
                            ->title('Status refreshed')
                            ->send();
                    }),
                Tables\Actions\Action::make('retry_import')
                    ->label('Retry import now')
                    ->icon('heroicon-o-arrow-path')
                    ->visible(fn (MediaSource $record): bool => $record->source_type === 'remote_fetch')
                    ->requiresConfirmation()
                    ->action(function (MediaSource $record): void {
                        app(MediaSourceService::class)->importRemoteNow($record);
                        $record->refresh();
                        app(MediaSourceService::class)->refreshAssetStatus($record->asset);
                        if ($record->status === 'failed') {
                            Notification::make()
                                ->danger()
                                ->title('Import retry failed')
                                ->body($record->failure_reason ?: 'Remote import failed.')
                                ->send();
                        } else {
                            Notification::make()
                                ->success()
                                ->title('Import retry completed')
                                ->body('Remote source imported successfully.')
                                ->send();
                        }
                    }),
                Tables\Actions\Action::make('queue_optimization')
                    ->label('Queue for optimization')
                    ->icon('heroicon-o-arrow-right-on-rectangle')
                    ->color('info')
                    ->visible(fn (MediaSource $record): bool => $record->status === 'ready' && in_array($record->optimize_status, ['pending', 'failed'], true))
                    ->form([
                        Forms\Components\Toggle::make('compress_enabled')
                            ->label('Compress to MP4 before playback/HLS')
                            ->default(true)
                            ->inline(false)
                            ->helperText('Recommended for large MKV/AVI uploads. Uses H.264 CRF compression + faststart and may delete the original source file when enabled in env.'),
                        Forms\Components\Toggle::make('hls_480p')
                            ->label('Generate 480p HLS')
                            ->default(true)
                            ->inline(false),
                        Forms\Components\Toggle::make('hls_720p')
                            ->label('Generate 720p HLS')
                            ->default(false)
                            ->inline(false),
                    ])
                    ->action(function (MediaSource $record, array $data): void {
                        $record->update([
                            'compress_enabled' => (bool) ($data['compress_enabled'] ?? true),
                            'source_metadata' => $this->mergeNbxMetadata($record, $this->nbxProcessingPayload($data, (string) $record->source_type)),
                        ]);
                        $queued = app(MediaSourceService::class)->queuePlaybackProcessing($record);
                        app(MediaSourceService::class)->refreshAssetStatus($record->asset);

                        $notification = Notification::make()
                            ->title($queued ? 'Queued for optimization' : 'Optimization already queued')
                            ->body($queued
                                ? 'Source has been sent to the worker (or local queue). Optimize status will update when processing completes.'
                                : 'This source already has optimization pending or running, so no duplicate job was dispatched.');

                        ($queued ? $notification->success() : $notification->warning())->send();
                    }),
                Tables\Actions\Action::make('run_reoptimise')
                    ->label('Run re-optimise')
                    ->icon('heroicon-o-cpu-chip')
                    ->color('info')
                    ->visible(fn (MediaSource $record): bool => $record->status === 'ready')
                    ->requiresConfirmation()
                    ->modalHeading('Re-optimise this source')
                    ->modalDescription('Re-run MP4 faststart and HLS generation for this source. The job will be queued and may take several minutes.')
                    ->form([
                        Forms\Components\Toggle::make('compress_enabled')
                            ->label('Compress to MP4 before playback/HLS')
                            ->default(true)
                            ->inline(false)
                            ->helperText('Keep enabled to reduce storage usage and generate a smaller _play MP4 before HLS.'),
                        Forms\Components\Toggle::make('hls_480p')
                            ->label('Generate 480p HLS')
                            ->default(true)
                            ->inline(false),
                        Forms\Components\Toggle::make('hls_720p')
                            ->label('Generate 720p HLS')
                            ->default(false)
                            ->inline(false),
                    ])
                    ->action(function (MediaSource $record, array $data): void {
                        $record->update([
                            'compress_enabled' => (bool) ($data['compress_enabled'] ?? true),
                            'source_metadata' => $this->mergeNbxMetadata($record, $this->nbxProcessingPayload($data, (string) $record->source_type)),
                        ]);
                        $queued = app(MediaSourceService::class)->queuePlaybackProcessing($record);
                        app(MediaSourceService::class)->refreshAssetStatus($record->asset);

                        $notification = Notification::make()
                            ->title($queued ? 'Re-optimise queued' : 'Optimization already queued')
                            ->body($queued
                                ? 'Optimization (MP4 faststart + HLS) has been queued. Progress will update in the table.'
                                : 'This source already has optimization pending or running, so no duplicate job was dispatched.');

                        ($queued ? $notification->success() : $notification->warning())->send();
                    }),
                Tables\Actions\Action::make('fetch_artifact_from_worker')
                    ->label('Fetch artifact from worker')
                    ->icon('heroicon-o-arrow-down-tray')
                    ->color('success')
                    ->visible(fn (MediaSource $record): bool => (bool) config('cdn.laravel_worker_enabled', false) && $record->status === 'ready')
                    ->fillForm(fn (MediaSource $record): array => [
                        'hls_worker_artifact_url' => $record->hls_worker_artifact_url ?? '',
                    ])
                    ->form([
                        Forms\Components\TextInput::make('hls_worker_artifact_url')
                            ->label('Worker artifact URL')
                            ->url()
                            ->required()
                            ->maxLength(2048)
                            ->placeholder('https://worker.../api/v1/artifacts/TOKEN')
                            ->helperText('Paste the full URL from the worker (e.g. Copy artifact URL in worker Filament). CDN will fetch the HLS ZIP with the configured token and install it to this source.'),
                    ])
                    ->modalHeading('Fetch HLS artifact from worker')
                    ->modalDescription('When the worker callback failed or the CDN did not receive the artifact, paste the artifact URL here. The CDN will download the ZIP (using CDN_LARAVEL_WORKER_API_TOKEN) and install HLS into this source\'s storage.')
                    ->action(function (MediaSource $record, array $data): void {
                        $url = trim((string) ($data['hls_worker_artifact_url'] ?? ''));
                        if ($url === '') {
                            Notification::make()
                                ->warning()
                                ->title('URL required')
                                ->body('Please enter the worker artifact URL.')
                                ->send();
                            return;
                        }
                        $record->update([
                            'hls_worker_artifact_url' => $url,
                            'hls_worker_status' => 'artifact_ready',
                        ]);
                        FetchWorkerHlsArtifactJob::dispatch($record->id);
                        app(MediaSourceService::class)->refreshAssetStatus($record->asset);
                        Notification::make()
                            ->success()
                            ->title('Fetch queued')
                            ->body('Artifact fetch has been queued. If the optimization queue is not running on the CDN server, use "Run fetch now" on this source to download and install the HLS ZIP immediately.')
                            ->send();
                    }),
                Tables\Actions\Action::make('run_fetch_artifact_now')
                    ->label('Run fetch now')
                    ->color('success')
                    ->icon('heroicon-o-arrow-down-tray')
                    ->visible(fn (MediaSource $record): bool => (bool) config('cdn.laravel_worker_enabled', false) && $record->hls_worker_status === 'artifact_ready' && ! empty($record->hls_worker_artifact_url))
                    ->modalHeading('Run artifact fetch now')
                    ->modalDescription('Run the artifact fetch immediately in this request (no queue). Use this when the optimization queue is not being processed and the worker has already completed. Large ZIPs may take several minutes.')
                    ->requiresConfirmation()
                    ->action(function (MediaSource $record): void {
                        @set_time_limit(900);
                        try {
                            FetchWorkerHlsArtifactJob::dispatchSync($record->id);
                            app(MediaSourceService::class)->refreshAssetStatus($record->asset);
                            Notification::make()
                                ->success()
                                ->title('Fetch completed')
                                ->body('HLS artifact was downloaded and installed. Check the HLS Worker column and the media folder.')
                                ->send();
                        } catch (\Throwable $e) {
                            Notification::make()
                                ->danger()
                                ->title('Fetch failed')
                                ->body($e->getMessage())
                                ->send();
                        }
                    }),
                Tables\Actions\Action::make('disable_source')
                    ->label('Disable source')
                    ->color('warning')
                    ->icon('heroicon-o-no-symbol')
                    ->visible(fn (MediaSource $record): bool => $record->is_active)
                    ->action(function (MediaSource $record): void {
                        $record->update(['is_active' => false]);
                        app(MediaSourceService::class)->refreshAssetStatus($record->asset);
                    }),
                Tables\Actions\DeleteAction::make()
                    ->after(fn () => app(MediaSourceService::class)->refreshAssetStatus($this->getOwnerRecord())),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\BulkAction::make('queue_optimization_bulk')
                        ->label('Queue selected for optimization')
                        ->icon('heroicon-o-arrow-right-on-rectangle')
                        ->color('info')
                        ->requiresConfirmation()
                        ->modalHeading('Queue for optimization')
                        ->modalDescription('Send selected ready sources to the worker (or local queue) for faststart + HLS. Only sources with status Ready and optimize_status Pending/Failed will be queued.')
                        ->form([
                            Forms\Components\Toggle::make('compress_enabled')
                                ->label('Compress to MP4 before playback/HLS')
                                ->default(true)
                                ->inline(false),
                        ])
                        ->action(function (\Illuminate\Database\Eloquent\Collection $records, array $data): void {
                            $service = app(MediaSourceService::class);
                            $queued = 0;
                            $compressEnabled = (bool) ($data['compress_enabled'] ?? true);
                            foreach ($records as $record) {
                                if ($record->status === 'ready' && in_array($record->optimize_status, ['pending', 'failed'], true)) {
                                    $record->update(['compress_enabled' => $compressEnabled]);
                                    if ($service->queuePlaybackProcessing($record)) {
                                        $queued++;
                                    }
                                }
                            }
                            $service->refreshAssetStatus($this->getOwnerRecord());
                            Notification::make()
                                ->success()
                                ->title('Queued for optimization')
                                ->body($queued > 0 ? "{$queued} source(s) queued." : 'No eligible sources (only ready sources with Pending/Failed optimize status are queued).')
                                ->send();
                        }),
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    private function formatBytes(int $bytes): string
    {
        $units = ['B', 'KB', 'MB', 'GB', 'TB'];
        $size = $bytes;
        $unit = 0;

        while ($size >= 1024 && $unit < count($units) - 1) {
            $size /= 1024;
            $unit++;
        }

        return round($size, 2) . ' ' . $units[$unit];
    }

    private function normalizeSourceUrl(mixed $sourceUrl, string $sourceType): ?string
    {
        if (! is_string($sourceUrl)) {
            return null;
        }

        $trimmed = trim($sourceUrl);
        if ($trimmed === '') {
            return null;
        }

        if ($sourceType === 'embed') {
            return $trimmed;
        }

        return MediaUrl::normalize($trimmed) ?? $trimmed;
    }

    private function nbxProcessingPayload(array $data, string $inputType): array
    {
        return [
            'storage_target' => (string) ($data['storage_target'] ?? config('nbx.default_storage', 'contabo')),
            'faststart' => (bool) ($data['faststart'] ?? config('nbx.default_faststart', true)),
            'compress_enabled' => (bool) ($data['compress_enabled'] ?? false),
            'hls_480p' => (bool) ($data['hls_480p'] ?? config('nbx.default_hls_480', true)),
            'hls_720p' => (bool) ($data['hls_720p'] ?? config('nbx.default_hls_720', false)),
            'hls_1080p' => (bool) ($data['hls_1080p'] ?? config('nbx.default_hls_1080', false)),
            'allow_downloads' => (bool) ($data['allow_downloads'] ?? true),
            'allow_hls_streaming' => (bool) ($data['allow_hls_streaming'] ?? true),
            'input_type' => $inputType,
        ];
    }

    private function nbxProcessingPayloadFromGet(Forms\Get $get, string $inputType): array
    {
        return $this->nbxProcessingPayload([
            'storage_target' => $get('storage_target'),
            'faststart' => $get('faststart'),
            'compress_enabled' => $get('compress_enabled'),
            'hls_480p' => $get('hls_480p'),
            'hls_720p' => $get('hls_720p'),
            'hls_1080p' => $get('hls_1080p'),
            'allow_downloads' => $get('allow_downloads'),
            'allow_hls_streaming' => $get('allow_hls_streaming'),
        ], $inputType);
    }

    private function mergeNbxMetadata(MediaSource $source, array $payload): array
    {
        $metadata = (array) ($source->source_metadata ?? []);
        $generated = app(NbxEngineService::class)->initialMetadata($payload, (string) ($payload['input_type'] ?? $source->source_type));

        return array_replace_recursive($metadata, $generated);
    }
}
